version: '3.6'
services:
    mysql-5.6.34-v1:
        image: registry.cn-shenzhen.aliyuncs.com/624508914/mysql:5.6.34
        ports:
            - 3306:3306
        volumes:
            - ~/Docker:/volumes_data
            - ~/Docker/container/mysql/5.6.34/v1/conf.d:/etc/mysql/conf.d
            - ~/Docker/container/mysql/5.6.34/v1/data:/var/lib/mysql
        privileged: true
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        container_name: mysql-5.6.34-v1

    mysql-5.7.20-v1:
        image: registry.cn-shenzhen.aliyuncs.com/624508914/mysql:5.7.20
        ports:
            - 3307:3306
        volumes:
            - ~/Docker:/volumes_data
            - ~/Docker/container/mysql/5.7.20/v1/conf.d:/etc/mysql/conf.d
            - ~/Docker/container/mysql/5.7.20/v1/data:/var/lib/mysql
        privileged: true
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        container_name: mysql-5.7.20-v1
        
    php-5.6.27-v1:
        image: registry.cn-shenzhen.aliyuncs.com/624508914/php:5.6.27
        volumes:
            - ~/Docker:/volumes_data
            - ~/Docker/container/php/5.6.27/v1/conf.d:/usr/local/etc/php/conf.d
        privileged: true
        container_name: php-5.6.27-v1

    php-7.2.3-v1:
        image: registry.cn-shenzhen.aliyuncs.com/624508914/php:7.2.3
        volumes:
            - ~/Docker:/volumes_data
            - ~/Docker/container/php/7.2.3/v1/conf.d:/usr/local/etc/php/conf.d
        privileged: true
        container_name: php-7.2.3-v1

    nginx-1.10.2-v1:
        image: registry.cn-shenzhen.aliyuncs.com/624508914/nginx:1.10.2
        ports:
            - 80:80
            - 443:443
        depends_on:
            - php-5.6.27-v1
            - php-7.2.3-v1
        volumes:
            - ~/Docker:/volumes_data
            - ~/Docker/container/nginx/1.10.2/v1/conf.d:/etc/nginx/conf.d
        privileged: true
        container_name: nginx-1.10.2-v1
    
    redis-4.0.0-v1:
        image: registry.cn-shenzhen.aliyuncs.com/624508914/redis:4.0.0
        volumes:
            - ~/Docker/container/redis/4.0.0/v1/data:/data
        privileged: true
        container_name: redis-4.0.0-v1

    elasticsearch-5.5.1-v1:
        image: registry.cn-shenzhen.aliyuncs.com/624508914/elasticsearch:5.5.1
        command: elasticsearch -Ecluster.name=dev -Enode.name=dev_node
        volumes:
            - ~/Docker/container/elasticsearch/5.5.1/v1/data:/usr/share/elasticsearch/data
            - ~/Docker/container/elasticsearch/5.5.1/v1/plugins/ik:/usr/share/elasticsearch/plugins/ik
            - ~/Docker/container/elasticsearch/5.5.1/v1/plugins/ingest-attachment:/usr/share/elasticsearch/plugins/ingest-attachment
            - ~/Docker/container/elasticsearch/5.5.1/v1/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml            
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            ES_JAVA_OPTS: "-Xms1g -Xmx1g"
        privileged: true
        container_name: elasticsearch-5.5.1-v1

    kibana-5.5.1-v1:
        image: registry.cn-shenzhen.aliyuncs.com/624508914/kibana:5.5.1
        ports:
            - 5601:5601
        volumes:
           - ~/Docker/container/kibana/5.5.1/v1/config/kibana.yml:/usr/share/kibana/config/kibana.yml
        depends_on:
            - elasticsearch-5.5.1-v1
        privileged: true
        container_name: kibana-5.5.1-v1

    rabbitmq-3.7.6-v1:
        image: docker.io/rabbitmq:3.7.6
        ports:
            - 15672:15672
        volumes:
            - ~/Docker:/volumes_data
            - ~/Docker/container/rabbitmq/3.7.6/v1/conf.d/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        privileged: true
        environment:
            RABBITMQ_DEFAULT_USER: yangyj
            RABBITMQ_DEFAULT_PASS: 123456
        container_name: rabbitmq-3.7.6-v1