version: '2'
services:

    disk_data:
        image: registry.cn-hangzhou.aliyuncs.com/624508914/centos:7.3.1611
        volumes:
            - ~/Docker:/disk_data
        privileged: true
        container_name: disk_data
        
    mysql:
        image: registry.cn-hangzhou.aliyuncs.com/624508914/mysql:5.6.34
        depends_on:
            - disk_data
        ports:
            - 3306:3306
        volumes:
            - ~/Docker/containers/mysql/conf.d:/etc/mysql/conf.d
            - ~/Docker/containers/mysql/data:/var/lib/mysql
        volumes_from:
            - disk_data
        privileged: true
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        container_name: mysql
        
    phpfpm_5.6.27:
        image: registry.cn-hangzhou.aliyuncs.com/624508914/php:5.6.27-fpm
        depends_on:
            - disk_data
            - mysql
        volumes:
            - ~/Docker/containers/php/5.6.27/conf.d:/usr/local/etc/php/conf.d
        volumes_from:
            - disk_data
        privileged: true
        container_name: phpfpm_5.6.27

    phpfpm_7.1.0:
        image: registry.cn-hangzhou.aliyuncs.com/624508914/php:7.1.0-fpm
        depends_on:
            - disk_data
            - mysql
        volumes:
            - ~/Docker/containers/php/7.1.0/conf.d:/usr/local/etc/php/conf.d
        volumes_from:
            - disk_data
        privileged: true
        container_name: phpfpm_7.1.0
        
    nginx:
        image: registry.cn-hangzhou.aliyuncs.com/624508914/nginx:1.10.2
        ports:
            - 80:80
            - 443:443
        depends_on:
            - disk_data
            - phpfpm_5.6.27
            - phpfpm_7.1.0
        volumes:
            - ~/Docker/containers/nginx/conf.d:/etc/nginx/conf.d
        volumes_from:
            - disk_data
        privileged: true
        container_name: nginx
    
    # elasticsearch:
    #     image: docker.io/elasticsearch:5.0.1
    #     # 集群设置 Ecluster.name：集群名称 Enode.name：集群节点服务器名称 
    #     command: elasticsearch -Ecluster.name=hucxiaoyao -Enode.name=hucxiaoyao_node
    #     depends_on:
    #         - disk_data
    #     volumes:
    #         - ~/Docker/containers/elasticsearch/data:/usr/share/elasticsearch/data
    #     volumes_from: 
    #         - disk_data
    #     ports:
    #         - 9200:9200
    #         - 9300:9300
    #     environment:
    #         ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    #     privileged: true
    #     container_name: elasticsearch

    ## Nginx负载均衡集群PHP后端服务
    # phpfpm_server_01:
    #     image: registry.cn-hangzhou.aliyuncs.com/624508914/php:5.6.27-fpm
    #     depends_on:
    #         - disk_data
    #         - mysql
    #     volumes:
    #         - ~/Docker/containers/php/conf.d:/usr/local/etc/php/conf.d
    #     volumes_from:
    #         - disk_data
    #     privileged: true
    #     container_name: phpfpm_server_01

    # phpfpm_server_02:
    #     image: registry.cn-hangzhou.aliyuncs.com/624508914/php:5.6.27-fpm
    #     depends_on:
    #         - disk_data
    #         - mysql
    #     volumes:
    #         - ~/Docker/containers/php/conf.d:/usr/local/etc/php/conf.d
    #     volumes_from:
    #         - disk_data
    #     privileged: true
    #     container_name: phpfpm_server_02

    # phpfpm_server_03:
    #     image: registry.cn-hangzhou.aliyuncs.com/624508914/php:5.6.27-fpm
    #     depends_on:
    #         - disk_data
    #         - mysql
    #     volumes:
    #         - ~/Docker/containers/php/conf.d:/usr/local/etc/php/conf.d
    #     volumes_from:
    #         - disk_data
    #     privileged: true
    #     container_name: phpfpm_server_03
